### ISSUE TITLE
As a module developer, I want to generate markdown documents for commands and the module, so that I can create the MAML help file

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/stitch#54]
## Definition of Done

The `Build` phase of the `docs` profile creates the external help xml file in the staging directory for each module

## Acceptance Criteria

- GIVEN a directory of properly formatted markdown files in the `docs/<module name>` directory, WHEN the `build` task is run, THEN the `<module name>-help.xml` file is created in the en-US directory in `staging` AND any additional language

## Tasks

- [ ] Create a `docs` build profile
- [ ] Create a task that generates a markdown file for each function
- [ ] Create a task that updates the markdown based on the comment-based help
- [ ] Create a task that fixes the language on codeblocks in PlatyPS
