### ISSUE TITLE
Every phase must be idempotent

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/stitch#81]
## Defining idempotency

When running `Invoke-Build`, any phase that is called will not alter the project if no changes are made in between each successive call.

## Validate
- [ ] Only create directories if they are not already present in the project
- [ ] Only install required modules if they are not already present in the project

## Test
- [ ] Only run the tests if any file in source or test has changed since the last test

## Build
- [x] #82
  - [ ] If any source file has changed
  - [ ] If any file no longer exists in staging
##
